[package]
name = "rust-gstream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.18.4"
glib = "0.18.4"
gstreamer = "0.21.3"
